kind: pipeline
type: docker
name: build
steps:
  - name: build jar
    image: openjdk:14-jdk-slim
    volumes:
      - name: cache_m2
        path: /root/.m2/repository
    commands:
      - ./mvnw package -Dmaven.test.skip=true -B
  - name: build jar
        image: docker
        commands:
          - docker build -t crowdsalat/kvb-rad
          - docker run -v /var/run/docker.sock:/var/run/docker.sock -p 8080:8080 --network=pgnetwork --name kvb-rad crowdsalat/kvb-rad
volumes:
  - name: cache_m2
    host:
      path: /tmp/drone/cache/m2/repository
