kind: pipeline
type: docker
name: build
steps:
  - name: build jar
    image: openjdk:14-jdk-slim
    volumes:
      - name: cache_m2
        path: /root/.m2/repository
    commands:
      - ./mvnw package -Dmaven.test.skip=true -B

volumes:
  - name: cache_m2
    host:
      path: /tmp/drone/cache/m2/repository
