kind: pipeline
type: docker
name: build
steps:
  - name: build jar
    image: openjdk:14-jdk-slim
    volumes:
      - name: cache_m2
        path: /root/.m2/repository
    commands:
      - ./mvnw package -Dmaven.test.skip=true -B
  - name: build and push docker image
    image: plugins/docker
    settings:
      username:
        from_secret: DOCKERHUB_USER
      password:
        from_secret: DOCKERHUB_PW
      repo: crowdsalat/kvb-rad
      tags:
        - latest
        - {DRONE_TAG}
  - name: start application
    image: docker/compose
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker-compose up -d --force-recreate

volumes:
  - name: cache_m2
    host:
      path: /tmp/drone/cache/m2/repository
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  event:
    - tag
