kind: pipeline
type: docker
name: build
steps:
  - name: build jar
    image: openjdk:14-jdk-slim
    commands:
      - pwd
      - printenv
      - ./mvnw help:system
      - ./mvnw help:effective-settings
      - ./mvnw -B package -Dmaven.test.skip=true
