kind: pipeline
type: docker
name: build
steps:
  - name: build jar
    image: openjdk:14-jdk-slim
    volumes:
      - name: cache_m2
        path: /root/.m2/repository
    commands:
      - ./mvnw package -Dmaven.test.skip=true -B
  - name: docker
    image: docker
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock
    commands:
      - docker build -t crowdsalat/kvb-rad .
      - docker run -p 8080:8080 --name kvb-rad crowdsalat/kvb-rad
volumes:
  - name: cache_m2
    host:
      path: /tmp/drone/cache/m2/repository
  - name: docker_sock
    host:
      path: /var/run/docker.sock

