name: ci

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Build with Maven
      run: mvn -B package -Dmaven.test.skip=true --file pom.xml
    - name: save artifcat
      uses: actions/upload-artifact@v2-preview
      with:
        name: app.jar
        path: target/*.jar
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          crowdsalat/kvb-rad:latest
          crowdsalat/kvb-rad:${{ github.ref_name}}
